INSERT INTO produto  VALUES (1, 'Esponja', 'Esponja para panela', NULL);
INSERT INTO produto  VALUES (2, 'Leite', ' Leite desnatado', NULL);
INSERT INTO produto  VALUES (3, 'Leite integral', 'Leite integral', 2);
INSERT INTO produto  VALUES (4, 'Leite condensado', 'Leite condensado', 2);
INSERT INTO produto  VALUES (5, 'Metal', 'Metal para uso diverso', NULL);
INSERT INTO produto  VALUES (6, 'Esponja', 'Esponja para polir bronze', 5);
INSERT INTO produto  VALUES (7, 'Hastes', 'Hastes para barbear', 5);
INSERT INTO produto  VALUES (8, 'Retrovisor', 'Retrovisor para moto', 5);
INSERT INTO produto  VALUES (9, 'Arroz', 'Arroz prato fino', NULL);
INSERT INTO produto  VALUES (10, 'Curativo', 'Curativo adesivo', NULL);
INSERT INTO produto  VALUES (11, 'Chiclete', 'Goma de mascar', NULL);

INSERT INTO imagem  VALUES (1, 'JPEG', 1);
INSERT INTO imagem  VALUES (2, 'BITMAP', 2);
INSERT INTO imagem  VALUES (3, 'GIF', 2);
INSERT INTO imagem  VALUES (4, 'JPEG', 2);
INSERT INTO imagem  VALUES (5, 'PNG', 3);
INSERT INTO imagem  VALUES (6, 'JPEG', 4);
INSERT INTO imagem  VALUES (7, 'JPEG', 5);
INSERT INTO imagem  VALUES (8, 'JPEG', 6);
INSERT INTO imagem  VALUES (9, 'JPEG', 7);
INSERT INTO imagem  VALUES (10, 'JPEG', 8);
INSERT INTO imagem  VALUES (11, 'JPEG', 9);
INSERT INTO imagem  VALUES (12, 'JPEG', 10);
INSERT INTO imagem  VALUES (13, 'JPEG', 11);
INSERT INTO imagem  VALUES (14, 'JPEG', 1);
INSERT INTO imagem  VALUES (15, 'BITMAP', 2);
INSERT INTO imagem  VALUES (16, 'GIF', 2);
INSERT INTO imagem  VALUES (17, 'JPEG', 2);
INSERT INTO imagem  VALUES (18, 'PNG', 3);
INSERT INTO imagem  VALUES (19, 'JPEG', 4);
INSERT INTO imagem  VALUES (20, 'JPEG', 5);
INSERT INTO imagem  VALUES (21, 'JPEG', 6);
INSERT INTO imagem  VALUES (22, 'JPEG', 7);
INSERT INTO imagem  VALUES (23, 'JPEG', 8);
INSERT INTO imagem  VALUES (24, 'JPEG', 9);
INSERT INTO imagem  VALUES (25, 'JPEG', 10);
INSERT INTO imagem  VALUES (26, 'JPEG', 11);
